[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ['derive'] }
url = "2.3.1"
reqwest = { version = "0.11.17", features = ['json', "blocking"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
error-stack = "0.3.1"

codegen = { path = "../../lib/codegen" }
skeletor = { path = "../../lib/skeletor" }
